### ISSUE TITLE
Do you have any roadMap?

### ISSUE THREAD

**Issue by jinqi166** [muqeet-khan/BlazorComponents#8]
Do you have any about BlazorComponents?

**Comment by muqeet-khan** [comment]
Because Blazor is itself experimental, I think having a specific roadmap does not make much sense. I should\will be making changes to make sure I keep BlazorComponents compatible and working with new versions of Blazor.  

If you are looking for something specific in terms of functionality let me know and I will see what I can do. 

Thanks for your interest in BlazorComponents.
